# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "osmtileserver"

  config.vm.network "forwarded_port", guest: 80, host: 8082
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.post_up_message = "osmtileserver is running at http://localhost:8082"

  config.vm.synced_folder "../data", "/data_share", type: "rsync"

  config.vm.provider "virtualbox" do |m|
    m.gui = false
    m.name = "osmtileserver"
    m.cpus = 2
    m.memory = 4096
  end

  config.vm.provision "shell", path: "../data/install.sh"
end
